apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-docker-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-docker-image
  template:
    metadata:
      labels:
        app: custom-docker-image
    spec:
      containers:
        - name: custom-docker-image
          image: cronde:v1
          # Add any additional configurations or environment variables as needed
          # ports:
          #   - containerPort: 3000
          # env:
          #   - name: ENV_VARIABLE
          #     value: "some_value"
          securityContext:
            privileged: true # Required for DinD support
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock # Mount Docker socket into the container for DinD support
