apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: myacr.azurecr.io/my-image:latest
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: acr-credentials
